
@startuml online-store
left to right direction

actor Cliente
actor "Pasarela de pago" as Pasarela

rectangle "Tienda Online" {
  usecase "Buscar productos" as UC1
  usecase "Ver carrito" as UC2
  usecase "Añadir al carrito" as UC3
  usecase "Realizar pedido" as UC4
  usecase "Identificarse" as UC5
  usecase "Registrarse" as UC6
  usecase "Pagar" as UC7
  usecase "Pagar con tarjeta" as UC8
  usecase "Pagar con transferencia" as UC9

  UC4 ..> UC5 : <<include>>
  UC6 ..> UC5 : <<extend>>
  UC7 <|-- UC8
  UC7 <|-- UC9
}

Cliente --> UC1
Cliente --> UC2
Cliente --> UC3
Cliente --> UC4
Cliente --> UC7
Pasarela --> UC7
@enduml