@startuml
left to right direction

actor Cliente

rectangle "Máquina de Café" {
  usecase "Introducir dinero" as UC1
  usecase "Seleccionar producto" as UC2
  usecase "Seleccionar azúcar" as UC3
  usecase "Dispensar producto" as UC4
  usecase "Devolver cambio" as UC5
  usecase "Cancelar" as UC6

  UC2 ..> UC3 : <<include>>
  UC4 ..> UC5 : <<include>>
  UC6 ..> UC5 : <<include>>
}

Cliente --> UC1
Cliente --> UC2
Cliente --> UC4
Cliente --> UC6
@enduml